# Generated by Django 2.2.8 on 2019-12-28 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petbottles', models.IntegerField()),
                ('plasticbags', models.IntegerField()),
                ('foodwrappers', models.IntegerField()),
                ('yogurtcontainers', models.IntegerField()),
                ('detergents', models.IntegerField()),
                ('shower', models.IntegerField()),
                ('toohbrushes', models.IntegerField()),
                ('toothpastes', models.IntegerField()),
                ('plasticCups', models.IntegerField()),
                ('straws', models.IntegerField()),
                ('dispensableCutlery', models.IntegerField()),
                ('plasticPlates', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
