# Generated by Django 2.2.8 on 2020-01-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaldashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='saved',
            field=models.IntegerField(default=0),
        ),
    ]
